#!/usr/bin/env bash

# Fetch only tracked branches
# Assume the local and remote branch have the same name

for remote in $(git for-each-ref --format='%(refname:short)' refs/remotes); do
  for head in $(git for-each-ref --format='%(refname:short)' refs/heads); do
    local=${remote#*/}

    [ $head != $local ] && continue                 # skip remote branches which don't exist locally

    git fetch origin $local:refs/remotes/origin/$local
  done
done
